// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuggaLuggaTD_2D.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuggaLuggaTD_2D.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261010161407_Revisions")]
    partial class Revisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Alliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Name")
                        .IsUnique();

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.AutoFightReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ambush")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<string>("FighterIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProvisionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Skirmish")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId", "CollectedAt");

                    b.ToTable("AutoFightReports");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.BloodiedCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecoversAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId", "CharacterId")
                        .IsUnique();

                    b.ToTable("BloodiedCharacters");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionRaid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AttackerWon")
                        .HasColumnType("boolean");

                    b.Property<int>("DefenderFaction")
                        .HasColumnType("integer");

                    b.Property<string>("DefenderUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("Hold")
                        .HasColumnType("bigint");

                    b.Property<double>("March")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RaidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolveAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ResolveDamage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "RaidedAt");

                    b.ToTable("FactionRaids");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionSeasonScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PointsPerHour")
                        .HasColumnType("double precision");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RegionsHeld")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<double>("SettledPoints")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "SeasonNumber", "Faction")
                        .IsUnique();

                    b.ToTable("FactionSeasonScores");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionSiege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Captured")
                        .HasColumnType("integer");

                    b.Property<int>("D20Roll")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeclaredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefenderUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<long?>("FrozenHold")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<double>("March")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MusterEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SortieArmyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortieEnemyLevel")
                        .HasColumnType("integer");

                    b.Property<double>("SortiePower")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SortieRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SortieStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortieWaves")
                        .HasColumnType("integer");

                    b.Property<bool?>("SortieWon")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "State");

                    b.HasIndex("State", "MusterEndsAt");

                    b.ToTable("FactionSieges");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BloodiedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastActedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "Faction")
                        .IsUnique();

                    b.ToTable("FactionStates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FirstStepsProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ChestOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Done")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("FirstStepsProgress");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.GameInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonLengthDays")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SeasonStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("GameInstances");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.GameSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SlotName")
                        .IsUnique();

                    b.ToTable("GameSaves");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiredCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Affinity")
                        .HasColumnType("smallint");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("Rarity")
                        .HasColumnType("smallint");

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SignatureId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "CharacterId")
                        .IsUnique();

                    b.ToTable("HiredCharacters");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiredWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Carry")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeBiome")
                        .HasColumnType("integer");

                    b.Property<double>("HoursWorked")
                        .HasColumnType("double precision");

                    b.Property<bool>("Keep")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LevelRolledTo")
                        .HasColumnType("integer");

                    b.Property<int>("LifetimeOutput")
                        .HasColumnType("integer");

                    b.Property<int>("Look")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("RatePerHour")
                        .HasColumnType("double precision");

                    b.Property<string>("Rolls")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RollsSeen")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonsServed")
                        .HasColumnType("integer");

                    b.Property<short?>("SecondTrade")
                        .HasColumnType("smallint");

                    b.Property<string>("SiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("Tier")
                        .HasColumnType("smallint");

                    b.Property<short>("Trade")
                        .HasColumnType("smallint");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "SiteId");

                    b.HasIndex("GameInstanceId", "UserId");

                    b.ToTable("HiredWorkers");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiringCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeBiome")
                        .HasColumnType("integer");

                    b.Property<int>("Look")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("SecondTrade")
                        .HasColumnType("smallint");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<short>("Tier")
                        .HasColumnType("smallint");

                    b.Property<short>("Trade")
                        .HasColumnType("smallint");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "Slot")
                        .IsUnique();

                    b.ToTable("HiringCandidates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiringState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastArrivalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefreshesSinceClear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("HiringStates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.InviteCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<int>("Uses")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.ItemGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("GameInstanceId", "ItemId")
                        .IsUnique();

                    b.HasIndex("GameInstanceId", "UserId");

                    b.ToTable("ItemGrants");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.ItemLedgerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdoptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AdoptedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("ItemLedgerStates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("UserId", "GameInstanceId", "DedupKey")
                        .IsUnique();

                    b.HasIndex("UserId", "GameInstanceId", "ReadAt", "OccurredAt");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.MarketplaceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerGameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerId")
                        .HasColumnType("text");

                    b.Property<long>("CollectedGold")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EarnedGold")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GoodsKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ItemData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.HasIndex("GameInstanceId", "Status");

                    b.HasIndex("Kind", "Status", "GoodsKey", "CreatedAt");

                    b.ToTable("MarketplaceListings");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerGameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("PlayerGameData");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerGold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<double>("GoldPerHour")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastSettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LifetimeFromClears")
                        .HasColumnType("double precision");

                    b.Property<double>("LifetimeFromHoldings")
                        .HasColumnType("double precision");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<double>("SettledGold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("PlayerGold");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "MaterialName")
                        .IsUnique();

                    b.ToTable("PlayerMaterials");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AmbushAt")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("AmbushRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AmbushRunStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ArrivesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("AutoFightCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoMode")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoOrder")
                        .HasColumnType("integer");

                    b.Property<string>("AutoRecentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutoRegionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("AutoSettledAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AutoStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AutoStepEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AutoTargetSiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("CharacterIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DepartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromSiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HaltedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RegionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouteJson")
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ToSiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId");

                    b.ToTable("PlayerParties");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HandedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfferJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "OfferId")
                        .IsUnique();

                    b.ToTable("PlayerQuests");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerSiteClear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WorldRewardsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId", "SiteId")
                        .IsUnique();

                    b.ToTable("PlayerSiteClears");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PveRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FighterIdsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId", "ClaimedAt");

                    b.ToTable("PveRuns");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.QuestBoardState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("Hour")
                        .HasColumnType("bigint");

                    b.Property<string>("Seen")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Set")
                        .HasColumnType("integer");

                    b.Property<string>("Taken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("QuestBoardStates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.RegionFortification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Spent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("ToLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "RegionId");

                    b.HasIndex("State", "CompletesAt");

                    b.ToTable("RegionFortifications");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.RegionRaid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AttackerWon")
                        .HasColumnType("boolean");

                    b.Property<string>("DefenderUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RaidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResolveAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ResolveDamage")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "RegionId", "RaidedAt");

                    b.HasIndex("GameInstanceId", "UserId", "RegionId", "RaidedAt");

                    b.ToTable("RegionRaids");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.SeasonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChestItemName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ChestOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("ChestRarity")
                        .HasColumnType("smallint");

                    b.Property<double>("ClearingPoints")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<double>("HoldingPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("RaidingPoints")
                        .HasColumnType("double precision");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RegionsHeld")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SeasonEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SeasonStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SeasonEndedAt");

                    b.HasIndex("GameInstanceId", "SeasonNumber", "Rank");

                    b.ToTable("SeasonResults");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.SeasonScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ClearingPoints")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<double>("HoldingPoints")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastSettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PointsPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("RaidingPoints")
                        .HasColumnType("double precision");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<double>("SettledPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameInstanceId", "UserId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("SeasonScores");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Siege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArmyCharacterIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AssaultEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssaultRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssaultStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttackerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeclaredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefenderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EncounterEnemyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("EncounterWaves")
                        .HasColumnType("integer");

                    b.Property<long?>("FrozenHold")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<double>("MarchingPower")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MusterEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackerUserId");

                    b.HasIndex("State", "AssaultEndsAt");

                    b.HasIndex("State", "MusterEndsAt");

                    b.HasIndex("GameInstanceId", "AttackerUserId", "State");

                    b.HasIndex("GameInstanceId", "RegionId", "State");

                    b.ToTable("Sieges");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernLure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Affinity")
                        .HasColumnType("smallint");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("MissedRestocks")
                        .HasColumnType("integer");

                    b.Property<int>("PendingStrength")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "Affinity")
                        .IsUnique();

                    b.ToTable("TavernLures");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernRecruit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Affinity")
                        .HasColumnType("smallint");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("Rarity")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SignatureId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId", "Slot")
                        .IsUnique();

                    b.ToTable("TavernRecruits");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("PurchasedRosterSlots")
                        .HasColumnType("integer");

                    b.Property<int>("RefreshesSinceClear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("TavernStates");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.UserBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlockerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerId");

                    b.HasIndex("BlockerId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.WarLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RecordedTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("RegionId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId", "SeasonNumber", "OccurredAt");

                    b.ToTable("WarLog");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.WorldViewGameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId")
                        .IsUnique();

                    b.ToTable("WorldViewGameData");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Alliance", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany("Alliances")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.AutoFightReport", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.BloodiedCharacter", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionRaid", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionSeasonScore", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionSiege", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FactionState", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.FirstStepsProgress", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Friendship", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.GameInstance", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Owner")
                        .WithMany("OwnedGameInstances")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.GameSave", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany("GameSaves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiredCharacter", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiredWorker", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiringCandidate", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.HiringState", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.ItemGrant", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Letter", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.MarketplaceListing", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Buyer")
                        .WithMany("MarketplaceListingsAsBuyer")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany("MarketplaceListings")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Seller")
                        .WithMany("MarketplaceListingsAsSeller")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("GameInstance");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerGameData", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany("PlayerGameData")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany("PlayerGameData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerGold", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerMaterial", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerParty", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerQuest", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PlayerSiteClear", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.PveRun", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.QuestBoardState", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.RegionFortification", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.RegionRaid", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.SeasonResult", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.SeasonScore", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.Siege", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernLure", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernRecruit", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.TavernState", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.UserBlock", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "BlockedUser")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuggaLuggaTD_2D.API.Models.ApplicationUser", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.WarLogEntry", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithMany()
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.WorldViewGameData", b =>
                {
                    b.HasOne("MuggaLuggaTD_2D.API.Models.GameInstance", "GameInstance")
                        .WithOne("WorldViewGameData")
                        .HasForeignKey("MuggaLuggaTD_2D.API.Models.WorldViewGameData", "GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.ApplicationUser", b =>
                {
                    b.Navigation("BlockedByUsers");

                    b.Navigation("BlockedUsers");

                    b.Navigation("GameSaves");

                    b.Navigation("MarketplaceListingsAsBuyer");

                    b.Navigation("MarketplaceListingsAsSeller");

                    b.Navigation("OwnedGameInstances");

                    b.Navigation("PlayerGameData");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });

            modelBuilder.Entity("MuggaLuggaTD_2D.API.Models.GameInstance", b =>
                {
                    b.Navigation("Alliances");

                    b.Navigation("MarketplaceListings");

                    b.Navigation("PlayerGameData");

                    b.Navigation("WorldViewGameData");
                });
#pragma warning restore 612, 618
        }
    }
}
